######################################################################
# Automatically generated by qmake (2.01a) mer. 1. novembre 11:49:49 2020
######################################################################

TEMPLATE = app
QT += webkit
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenPrincipale.h
SOURCES += FenPrincipale.cpp main.cpp
